Lesson5
kurmangaliyev-a/Kolesa-Upgrade-FE-2021 pull request #5
Opened 2021-10-10 23:04 UTC by kurmangaliyev-a

![image](https://user-images.githubusercontent.com/40716296/136715692-f031ecde-8e65-48c1-84e6-6178977b8da7.png)

можно добавлять элементы через POST: http://api.mcdir.me/api/v1/product ;

2021-10-10 23:04 UTC, kurmangaliyev-a commented
Допишу сегодня доп задания и добавлю больше элементов

2021-10-13 02:55 UTC, airtwister requested changes

2021-10-13 02:55 UTC, airtwister commented on src/js/main.js
> +        let ballsInRus;
balls - это мячи) лучше points

и эта у тебя повторяется, надо вынести в отдельную функцию

2021-10-13 02:55 UTC, airtwister commented on src/js/main.js
> +        product.append(img);
такая верстка очень сложно читается, лучше прям шаблон писать:
```
<div class="product">
    <div class="product__info">
         ...
    </div>
    <div>...</div>
</div>
``` 
и т.д.

2021-10-13 02:55 UTC, airtwister commented on src/js/main.js
> +getCards();
по неймингу, get  - озаначает, что что-то вернется, тут и выше не подходит, нужно render или init

2021-10-14 04:08 UTC, airtwister approved these changes
не дождался правок в течение суток
можешь поправить для себя и замержить

2021-10-18 20:46 UTC, merged